#+title: readme

* Shapeless Editor
This is an experimental editor written in Jai that mimic the feel of
my everyday Emacs usage, with inspirations from 4coder's extension
method.

* Feature
Jai and Jai only. With how powerful the Jai language is. I feel like
that the lispy way of extending an editor is not the only way to do
so.

* Dependencies
- harfbuzz
- icu
- freetype (If color emoji is not needed, this can be ditched.)
- stb_truetype
- fontconfig (For finding system fonts)
- libgrepheme (A suckless alternative)

* msdf script
If you use -allglyphs, you won't have a unicode to match the thing.
#+begin_src shell
  msdf-atlas-gen -charset charset.txt -yorigin top -font ./Hack-Regular.ttf -format png -size 32 -imageout hack.png -json hack.json
#+end_src

In charset.txt
#+begin_src txt
  [0x20, 0x7E]
#+end_src

If you are using harfbuzz, because it gives a codepoint to the index
of the font, you should not use -charset.
#+begin_src shell
  msdf-atlas-gen -type mtsdf -allglyphs -yorigin top -font ./Hack-Regular.ttf -format png -emrange 0.5 -size 64 -imageout hack.png -json hack.json
#+end_src

* Unicode block
ftp://ftp.unicode.org/Public/UNIDATA/Blocks.txt

* Image format for msdf atlas image
Must not use R8G8B8A8_SRGB, it results in very blurry and thin font.

Use R8G8B8A8_UNORM.

I tracked down this bug for two days.
